apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelmcp.fullname" . }}-api
  labels:
    {{- include "sentinelmcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sentinelmcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
---
{{- if .Values.dashboard.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinelmcp.fullname" . }}-dashboard
  labels:
    {{- include "sentinelmcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.dashboardPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sentinelmcp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: dashboard
{{- end }}
